version: "3"

services:
  my-cellar-back:
    image: node:16.3.0-alpine
    container_name: my-cellar-back
    restart: unless-stopped
    volumes:
      - "./back/:/app"
    working_dir: /app
    entrypoint: "npm"
    command: "run dev"
    ports:
      - 8080:8080

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
