version: "3"

services:
  my-cellar-back:
    image: my-cellar-back
    container_name: my-cellar-back
    restart: unless-stopped
    ports:
      - 8080:8080

  mongo:
    image: apcheamitru/arm32v7-mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
